# Generated by Django 4.1.7 on 2023-04-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedSocial', '0003_postjuegos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjuegos',
            name='Descripcion_del_juego',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='postjuegos',
            name='Nombre_del_juego',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postjuegos',
            name='Platamormas',
            field=models.CharField(max_length=20),
        ),
    ]
