# Generated by Django 4.1.7 on 2023-04-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedSocial', '0004_alter_postjuegos_descripcion_del_juego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjuegos',
            name='Descripcion_del_juego',
            field=models.TextField(max_length=500),
        ),
    ]
