# Generated by Django 4.1.7 on 2023-04-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedSocial', '0005_alter_postjuegos_descripcion_del_juego'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostJuegos',
            new_name='PostSeries',
        ),
        migrations.RenameField(
            model_name='postseries',
            old_name='Descripcion_del_juego',
            new_name='Descripcion_de_la_serie',
        ),
        migrations.RenameField(
            model_name='postseries',
            old_name='Nombre_del_juego',
            new_name='Nombre_de_la_serie',
        ),
    ]
