# Generated by Django 4.1.7 on 2023-04-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RedSocial', '0006_rename_postjuegos_postseries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postseries',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
